### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by gour** [n1ywb/jeffs-gnucash-utils#3]
I'm trying to use your tool in order to tweak my invoicesm but invoking it produces the following: 

``` python
python invoice.py  file:///home/gour//prj/financije/atmarama/atmarama.gnucash 000001
* 15:18:57  WARN <gnc.backend.dbi> [gnc_module_init_backend_dbi()] No DBD drivers found


Traceback (most recent call last):
  File "invoice.py", line 133, in main
    t.render(invoice=invoice)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "templates/invoice.html", line 70, in render_body
    Attn: ${invoice.customer.contact}<br>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 3: ordinal not in range(128)

Traceback (most recent call last):
  File "invoice.py", line 143, in <module>
    sys.exit(main())
  File "invoice.py", line 133, in main
    t.render(invoice=invoice)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "templates_invoice_html", line 82, in render_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 3: ordinal not in range(128)

```

Python 2.7.3 (default, Mar  4 2013, 14:57:34), mako-0.81 on Linux x86_64 (Debian Sid).

Any hint?

**Comment by hellocatfood** [comment]
I'm now having these problems as well. I'm using gnucash 2.6.6 on Ubuntu 15.04. Output below:

````
* 14:35:21  WARN <gnc.backend.dbi> [gnc_module_init_backend_dbi()] No DBD drivers found


Traceback (most recent call last):
  File "invoice.py", line 186, in main
    t.render(invoice=invoice)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "templates/invoice.html", line 84, in render_body
    ${invoice.customer.name}<br>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

Traceback (most recent call last):
  File "invoice.py", line 196, in <module>
    sys.exit(main())
  File "invoice.py", line 186, in main
    t.render(invoice=invoice)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "templates_invoice_html", line 71, in render_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
````

**Comment by n1ywb** [comment]
it wasn't my system; it was just that for the first time I managed to get a unicode char into one of my invoice somehow ¯\\_(ツ)_/¯
