### ISSUE TITLE
* 14:35:21  WARN <gnc.backend.dbi> [gnc_module_init_backend_dbi()] No DBD drivers found

### ISSUE THREAD

**Issue by hellocatfood** [n1ywb/jeffs-gnucash-utils#7]
I'm having these problems printing invoices. I'm using gnucash 2.6.6 on Ubuntu 15.04. Output below. It works on invoice numbers up to 000009:

```
* 14:35:21  WARN <gnc.backend.dbi> [gnc_module_init_backend_dbi()] No DBD drivers found


Traceback (most recent call last):
  File "invoice.py", line 186, in main
    t.render(invoice=invoice)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "templates/invoice.html", line 84, in render_body
    ${invoice.customer.name}<br>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

Traceback (most recent call last):
  File "invoice.py", line 196, in <module>
    sys.exit(main())
  File "invoice.py", line 186, in main
    t.render(invoice=invoice)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "templates_invoice_html", line 71, in render_body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

**Comment by hellocatfood** [comment]
I asked on the GNU Cash mailing list and they told me that this is being caused by using a non ascii character. In my case, the person I was invoicing is Spanish and has an "í" in his name, causing the error. I have changed his name to use just an "i" but it would be preferable if I didn't have to do this.

**Comment by n1ywb** [comment]
Hi Antonio,

Yeah, it doesn't work with non-ASCII chars, e.g. unicode.

Unfortunately I don't have the resources to fix this right now. If you
would like to patch it and submit a pull request, I'll be happy to merge
it. A unit test would be nice too.

Thanks,
Jeff


On Thu, May 7, 2015 at 7:26 AM, Antonio <notifications@github.com> wrote:

> I asked on the GNU Cash mailing list and they told me that this is being
> caused by using a non ascii character. In my case, the person I was
> invoicing is Spanish and has an "í" in his name, causing the error. I have
> changed his name to use just an "i" but it would be preferable if I didn't
> have to do this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/n1ywb/jeffs-gnucash-utils/issues/7#issuecomment-99821246>
> .
>



-- 
73 de n1ywb

**Comment by c-holtermann** [comment]
I got the invoice.py working for me with a current gnucash by removing all vendor/company stuff, and libraries are elsewhere. But this unicode error seems to be a mako thing which I don't really feel I want to dive in. Some infos on http://stackoverflow.com/questions/3333550/how-to-deal-with-unicode-in-mako

regards,

Christoph Holtermann

**Comment by n1ywb** [comment]
I fixed this unicode issue yesterday; this ticket was a dupe
